### ISSUE TITLE
Please review thing.txt

### ISSUE THREAD

**Issue by biancapower** [biancapower/laughing-robot#1]
# Please provide your thoughts on the contents of thing.txt
- Section One @qwutony 
- Two @JiaChengOng96

**Comment by JiaChengOng96** [comment]
@biancapower Can't help ,there is nothing. Sorry =(

**Comment by qwutony** [comment]
# I think
## the file name
### is kinda
#### vague

**Comment by biancapower** [comment]
> # I think
> ## the file name
> ### is kinda
> #### vague

Thanks @qwutony , fixed.
